# Generated by Django 3.2.3 on 2021-05-30 17:43

from django.db import migrations, models
import django.utils.timezone
import feed.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=feed.models.uuid_name_upload_to)),
                ('body', models.TextField(help_text='본문을 입력하세요')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
