# Generated by Django 3.2.3 on 2021-06-04 06:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20210603_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 5, 6, 44, 14, 905902, tzinfo=utc), null=True, verbose_name='그룹 마침일'),
        ),
        migrations.AlterField(
            model_name='groupcommunitypost',
            name='body',
            field=models.TextField(help_text='내용'),
        ),
        migrations.AlterField(
            model_name='groupnotice',
            name='body',
            field=models.TextField(help_text='내용'),
        ),
        migrations.AlterModelTable(
            name='groupcommunitypost',
            table='group_community_post',
        ),
        migrations.AlterModelTable(
            name='groupnotice',
            table='group_notice',
        ),
    ]
