# Generated by Django 3.2.3 on 2021-06-04 07:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0003_auto_20210604_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 5, 7, 14, 33, 618685, tzinfo=utc), null=True, verbose_name='그룹 마침일'),
        ),
        migrations.CreateModel(
            name='GroupCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=127, null=True)),
                ('body', models.TextField(help_text='내용')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('plan_date', models.DateTimeField()),
                ('group', models.ForeignKey(help_text='그룹', on_delete=django.db.models.deletion.CASCADE, to='group.group')),
                ('user', models.ForeignKey(help_text='유저', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_calendarjhp',
            },
        ),
    ]
