# Generated by Django 3.2.3 on 2021-06-04 07:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_auto_20210604_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 5, 7, 16, 22, 230157, tzinfo=utc), null=True, verbose_name='그룹 마침일'),
        ),
        migrations.AlterModelTable(
            name='groupcalendar',
            table='group_calendar',
        ),
    ]
