# Generated by Django 3.2.3 on 2021-06-05 06:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20210604_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 6, 6, 58, 34, 52301, tzinfo=utc), null=True, verbose_name='그룹 마침일'),
        ),
        migrations.AlterField(
            model_name='groupcalendar',
            name='plan_date',
            field=models.DateTimeField(null=True),
        ),
    ]
