# Generated by Django 3.2.3 on 2021-06-25 09:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_alter_group_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 26, 9, 56, 52, 549309, tzinfo=utc), null=True, verbose_name='그룹 마침일'),
        ),
    ]
