# Generated by Django 3.2.3 on 2021-06-28 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_auto_20210628_1635'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_count', models.PositiveIntegerField(default=1)),
                ('activate_date', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('payment_fee', models.PositiveIntegerField(default=0)),
                ('payment_method', models.CharField(blank=True, choices=[('무통장 입금', '무통장 입금'), ('계좌 이체', '계좌 이체')], max_length=30, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_set', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_set', to='accounts.profile')),
            ],
        ),
    ]
