# Generated by Django 3.2.3 on 2021-07-02 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_user_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('created_at',)},
        ),
    ]
