# Generated by Django 3.2.3 on 2021-05-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('region_type', models.CharField(choices=[('first_region', '성동구, 광진구, 성북구'), ('second_region', '서초구, 강남구'), ('third_region', '용산구, 중구, 종로구'), ('fourth_region', '여의도구, 영등포구'), ('fifth_region', '도봉구, 강북구, 노원구'), ('sixth_region', '양천구, 강서구, 구로구, 영등포구'), ('seventh_region', '서대문구, 은평구'), ('eighth_region', '관악구, 금천구, 동장구')], default='first_region', help_text='지역 등록', max_length=30)),
                ('interest_type1', models.CharField(choices=[('Computer', '컴퓨터'), ('English', '영어'), ('University_entrance', '대입'), ('Certificate', '자격증'), ('Foreign_language', '외국어'), ('Design', '디자인'), ('Interview', '면접'), ('Etc', '기타'), ('None', '없음')], default='None', max_length=30)),
                ('interest_type2', models.CharField(choices=[('Computer', '컴퓨터'), ('English', '영어'), ('University_entrance', '대입'), ('Certificate', '자격증'), ('Foreign_language', '외국어'), ('Design', '디자인'), ('Interview', '면접'), ('Etc', '기타'), ('None', '없음')], default='None', max_length=30)),
                ('interest_type3', models.CharField(choices=[('Computer', '컴퓨터'), ('English', '영어'), ('University_entrance', '대입'), ('Certificate', '자격증'), ('Foreign_language', '외국어'), ('Design', '디자인'), ('Interview', '면접'), ('Etc', '기타'), ('None', '없음')], default='None', max_length=30)),
                ('nickname', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('phone_number', models.CharField(max_length=14, null=True, unique=True)),
                ('withdrew_at', models.DateTimeField(blank=True, null=True, verbose_name='탈퇴 시점')),
                ('birth_day', models.CharField(blank=True, help_text='생년월일', max_length=32)),
                ('is_login', models.BooleanField(default=False)),
                ('is_signup_first_step', models.BooleanField(default=False)),
                ('is_signup_finish', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
