# Generated by Django 3.2.3 on 2021-06-02 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_from_set', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_to_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_type', models.CharField(choices=[('email', 'EMAIL'), ('kakao', 'KAKAO'), ('naver', 'NAVER'), ('facebook', 'FACEBOOK'), ('instagram', 'INSTAGRAM')], default='email', help_text='회원가입 방식', max_length=10)),
                ('short_introduce', models.CharField(blank=True, max_length=511, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('device_token', models.CharField(blank=True, help_text='notification 기기 고유 토크값', max_length=512, null=True)),
                ('is_push', models.BooleanField(default=True, help_text='notification 수신 여부')),
                ('popularity_score', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.OneToOneField(help_text='유저', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='followed', through='accounts.UserFollow', to=settings.AUTH_USER_MODEL),
        ),
    ]
