# Generated by Django 3.2.3 on 2021-06-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210602_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='interest_type1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='interest_type2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='interest_type3',
        ),
        migrations.RemoveField(
            model_name='user',
            name='region_type',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
