# Generated by Django 3.2.3 on 2021-06-28 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.CreateModel(
            name='ProfileIntroduce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/profile_introduce')),
                ('description', models.CharField(blank=True, max_length=511, null=True)),
                ('profile', models.ForeignKey(help_text='유저 프로필', on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
