# Generated by Django 3.2.3 on 2021-06-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210628_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='service_one_time',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='service_price',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
