# Generated by Django 3.2.3 on 2021-07-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='service_price',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
